<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:include schemaLocation="Common.xsd"/>
  <xs:include schemaLocation="Product.xsd"/>
  <xs:annotation>
    <xs:documentation>
      List of products and product variants.
      If the product is discontinued, but there are still some items available
      set Clearance element to value "true".
      If, on the other hand, the product is discontinued and out of stock
      remove it from the XML file completely, and it will be automatically deactivated.
    </xs:documentation>
  </xs:annotation>

  <xs:element name="Products">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Product" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>

    <xs:unique name="UniqueSKU">
      <xs:selector xpath="Product"/>
      <xs:field xpath="SKU"/>
    </xs:unique>
    <xs:unique name="UniqueVariantSKU">
      <xs:selector xpath="Product/Variants/Variant"/>
      <xs:field xpath="SKU"/>
    </xs:unique>
  </xs:element>
</xs:schema>
